[project]
name = "lidar-hd"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "numpy==2.3.4",
    "laspy[lazrs]>=2.7",
    "pillow>=11",
    "py3dtiles>=12.1",
    "pyproj>=3.7",
    "textual>=8",
    "minio>=7.2",
    "python-dotenv>=1.0",
    "rasterio>=1.5.1",
    "pmtiles>=3.8.1",
]
